-- MySQL Script generated by MySQL Workbench
-- Sat 01 Dec 2018 09:24:56 PM -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `registry` VARCHAR(45) NULL,
  `receive_email` TINYINT(1) NOT NULL DEFAULT 1,
  `level` INT NOT NULL DEFAULT 0,
  `phone` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  `about` TEXT(1024) NULL,
  `photo` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oportunity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oportunity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creator_id` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `approved` TINYINT(1) NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 0,
  `description` TEXT(2048) NULL,
  `inscription` TEXT(1024) NULL,
  `photo` VARCHAR(128) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_oportunity_user_idx` (`creator_id` ASC),
  CONSTRAINT `fk_oportunity_user`
    FOREIGN KEY (`creator_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interest` (
  `user_id` INT NOT NULL,
  `oportunity_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `oportunity_id`),
  INDEX `fk_user_has_oportunity_oportunity1_idx` (`oportunity_id` ASC),
  INDEX `fk_user_has_oportunity_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_oportunity_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_oportunity_oportunity1`
    FOREIGN KEY (`oportunity_id`)
    REFERENCES `oportunity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
